name: Update README

on:
  schedule:
    - cron: "0 0 * * *" # Exécute tous les jours à minuit (UTC)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"

      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@e856fc8de9d7729b463c468911e232cfbdc3d55e # v2.0.2
        with:
          card: stats
          options: username=FWICSS&theme=dark&hide_border=true&show_icons=true
          path: assets/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: stats-organization/github-readme-stats-action@e856fc8de9d7729b463c468911e232cfbdc3d55e # v2.0.2
        with:
          card: top-langs
          options: username=FWICSS&theme=dark&hide_border=true&layout=compact&langs_count=8
          path: assets/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README
        run: node index.js

      - name: Commit changes
        run: |
          git config --global user.name "dim-sDev"
          git config --global user.email "dimitriaigle@gmail.com"
          git add .
          git commit -m "Update README with dynamic content" || true
          git push
